server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://aria-backend:4001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
        proxy_set_header x-api-key $http_x_api_key;
        proxy_set_header x-aria-key $http_x_aria_key;
    }

    location /health {
        proxy_pass http://aria-backend:4001;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
